#!/bin/bash

pip3 uninstall angie-sirius -y
pip3 uninstall lina -y
pip3 uninstall parade -y
pip3 uninstall cad -y
pip3 uninstall sirius -y
pip3 uninstall mist-dispersion -y
pip3 uninstall phalanx -y

